### PR TITLE
feat: filter by priority (hide green priority level)

### PR DESCRIPTION
**Pull request by putsi**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Currently, comments can only be filtered based on commit and filename.

## What is the new behavior?

This feature adds a new filter button to the Comment Explorer that allows filtering based on priority.
The new filter is currently hard-coded to hide all comments that have green priority level.

This is useful for security code reviews where the comments can initially be red/yellow/unknown priority and after examination, are marked as green if there is no vulnerability. By filtering away the green priorities, the user interface stays cleaner for the security code review process.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

In the future, it might be good idea to support user-selectable priority levels for the filtering.

### CODE REVIEW

**Comment by d-koppenhagen** [comment]
I like the Ides/contribution. The only thing that should be changes is the icon from this new filter as the common filter icon is already used:
https://github.com/d-koppenhagen/vscode-code-review/blob/master/package.json#L91-L106

Bildschirm­foto 2022-12-21 um 21 06 19


Bildschirm­foto 2022-12-21 um 21 02 49

Can you make a suggestion to better distinguish those two filters?

**Review by d-koppenhagen — CHANGES_REQUESTED** [review]
I like the Ides/contribution. The only thing that should be changes is the icon from this new filter as the common filter icon is already used:
https://github.com/d-koppenhagen/vscode-code-review/blob/master/package.json#L91-L106

Bildschirm­foto 2022-12-21 um 21 06 19


Bildschirm­foto 2022-12-21 um 21 02 49

Can you make a suggestion to better distinguish those two filters?

**Comment by putsi** [comment]
Hi @d-koppenhagen,

I think maybe using `layers` and `layers-active` from https://microsoft.github.io/vscode-codicons/dist/codicon.html

image

Should I make a commit for that?
Should I make the active icon color to red as with the other filter?

**Review by d-koppenhagen — APPROVED** [review]

**Comment by d-koppenhagen** [comment]
@all-contributors add @putsi for code

**Comment by d-koppenhagen** [comment]
Thanks @putsi . The Features has been released with version 1.33.1.

**Pull request merged**
